### ISSUE TITLE
Resumo

### ISSUE THREAD

**Issue by farosas** [UTFPR-PG/latex#10]
O resumo provavelmente está fora das normas também. A não ser que a abntex2 possua algum comando para fazer aquela parte estranha no começo do resumo.

**Comment by farosas** [comment]
Para a referência inicial do resumo, o trecho:

```
\citetext{<key>}\par
\vspace{\onelineskip}
```

quase faz o serviço, mas a entrada aparece na lista de referências, além de ficar um pouco poluído e não ter como fazer de maneira automatizada. ~~Mas para aqueles que estão com pressa, deve servir. Para remover da lista de referências, será preciso editar o .bbl.~~ EDIT: Se deletar do .bbl, perde a citação, logo, não funciona. Ver comentário seguinte.

**Comment by farosas** [comment]
Consegui uma maneira mais robusta de fazer isso com o pacote `multibib`. Ele permite definir bibliografias adicionais com uma "label" e cria novos comandos (\citelabel, \nocitelabel, \bibliographylabel, etc.). Dessa forma, eu posso usar \nociteMy{meu_artigo} e colocar \bibliographyMy{bib} dentro do resumo para exibir a citação dentro do resumo. No final do documento, ainda haverá o \bibliography{bib} normal e as citações ainda funcionam normalmente.

O único problema é que em algum lugar existe um \newpage, \clearpage ou \pagebreak que faz a bibliografia começar em uma nova página. Para a bibliografia normal, isto é o correto, porém para esta bibliografia alternativa que vai dentro do resumo, não.

MWE: 

```
git clone https://gist.github.com/87f0ad927c5318142894.git

pdflatex test.tex
bibtex test.aux
bibtex this.aux
pdflatex test.tex
pdflatex test.tex
```

**Comment by gbc921** [comment]
Será que para a primeira opção com `\citetextkey` não existe a opção '*' para remover de citações?

**Comment by farosas** [comment]
Não, mas sinta-se à vontade para escrever uma: `/usr/share/texmf-dist/tex/latex/abntex2cite.sty` linha 1148
