### ISSUE TITLE
Tamanho da fonte do número da página

### ISSUE THREAD

**Issue by gbc921** [UTFPR-PG/latex#14]
"Reparei" que toda página que ocorre um capítulo novo, o tamanho da fonte do número da página é reduzido.

Pra mim, isso também se relaciona ao fato de toda linha que representa o capítulo aparecer em negrito no sumário.

**Comment by farosas** [comment]
Só fazendo um update aqui. Já encontrei a solução para o problema. Eu tinha feito um prehook no `\textual` para colocar `\pagestyle{simple}`. Mas dentro do `\textual` o abntex2 muda o pagestyle para abntheadings. Em abntheadings tem: 

```
\makeoddhead{abntchapfirst}{}{}{\ABNTEXfontereduzida\thepage}
```
