### ISSUE TITLE
Referência no início do resumo

### ISSUE THREAD

**Issue by farosas** [UTFPR-PG/latex#17]
A referência no início do resumo está incorreta. É necessário que o nome do autor esteja por extenso e o ano de publicação deve aparecer duas vezes. Existem as opções `abnt-full-initials=yes` e `abnt-thesis-year=both` que fazem isso, porém a sua utilização não tem efeito porque a referência do resumo utiliza o estilo da abntex "hardcoded". Existem motivos para isto, confira o issue #10.

**Comment by farosas** [comment]
Eu consegui uma solução temporária. O commit 33bcf74 adiciona as opções `abnt-full-initials=no` e `abnt-thesis-year=final`. Estes são os valores padrão, nada está sendo modificado, porém agora podemos editar o arquivo abntex2-alf.bst e afetar apenas a referência do resumo, sem modificar as referências do texto. Segue o patch:

https://gist.github.com/fabianorosas/f09b371fccec0c989096

P.S.: Eu sei que isso é totalmente inaceitável. Mas o pessoal precisa se formar.

**Comment by gbc921** [comment]
Apliquei o patch e não resolveu, para mim. :disappointed_relieved:

O nome aparece de forma completa, ou da mesma maneira que você insere no `.bib`.

O problema está no ano que só acontece uma vez, depois do título do trabalho.

[Naquele "modelo" word, na página 20, existe um exemplo de como deve ser essa autocitação][1]. Para o problema do ano, na entrada `Note` do `.bib` eu escrevo o ano e ele aparece no fim da frase. Para o caso do título em negrito a solução imediata foi editar o [`Title` do `.bib` com `\textbf{}`][2]. Por enquanto também não se deve utilizar o campo `Address` pois ele aparece depois do título do trabalho, devendo aparecer somente após a impressão do nome completo da Universidade.

[1]:

```
SOBRENOME, Prenome do Autor do Trabalho. Título do trabalho: subtítulo (se houver).  Ano de defesa. Número total de folhas. Trabalho de Conclusão de Curso (Bacharelado ou Tecnologia em [nome do curso]) ou Monografia (Especialização em [nome do curso]) ou Dissertação (Mestrado em [nome do curso]) - Universidade Tecnológica Federal do Paraná. Ponta Grossa, ano de defesa.
```

[2]: `Title = {\textbf{Implementação de workarounds para normas da UTFPR no abntex}},`

EDIT: Mais informações e workarounds

**Comment by farosas** [comment]
Se o patch funcionou para o nome, tem que ter funcionado para o ano também ué. A única coisa que interefere na referência do resumo é o .bst onde foi aplicado o patch. Nenhuma outra configuração no documento tem efeito porque o multibib usa uma bibliografia à parte.

Talvez tenha alguma discrepância com relação ao .bib. Coloca o seu aqui pra eu dar uma olhada como está.

O título não precisa ser em negrito. Precisa de ênfase. Mas se você quiser usar negrito o esquema seria editar o .bst:
`"\emph" 'abnt.emphasize :=` --> `"\bf" 'abnt.emphasize :=`

Quem sabe o mais correto seja nós termos um .bst próprio e fazer o multibib usar ele ao invés do da abntex. O problema seria ter mais um arquivo pra cuidar.

**Comment by gbc921** [comment]
Não é que funcionou para o nome. Ele teoricamente deu certo. Haha
Ele imprime exatamente o que coloco no `Author`, entendendo o que é nome/sobrenome.

Como está seu `Author`?

Acredito que sua idéia do `.bst` seja a mais viável. É mais um arquivo, mas isso não muda né.

**Comment by farosas** [comment]
Mas é esse o comportamento esperado. Você quer que ele adivinhe o nome do
autor? auehaue

o meu:
`author={Fabiano Almeida Rosas}`

Então, o que eu queria mesmo era passar alguns parâmetros e pronto. Por que
o problema é que nós não estamos usando um estilo bibliográfico. Isso é
feito em algum lugar quando usamos o pacote _abntex2cite_. Ai é como se o
abntex2cite "não reconhecesse" a bibliografia do resumo. E eu também acho
que o multibib exige que usemos o comando `bibliographystyle`. Eu vou dar
uma pesquisada nisso hoje.

**Comment by gbc921** [comment]
O pior que na formatação do bib ele consegue saber os 3 nomes.

No meu tá `author={CASELLA, Gabriel Bolognani}`, então ele sabe meu último nome, inicial e _middle name_. Por isso a opção do abntex de colocar o nome abreviado ou não.

**Comment by farosas** [comment]
15498fee8 substitui o comando `\refthis` pelo comando `\autocitacao`, que cria automaticamente uma bibliografia para a autocitação, a partir dos dados fornecidos no preâmbulo do arquivo.

Caso o usuário tenha algum requisito especial, ele pode substituir o arquivo gerado automaticamente por um de sua autoria, (desde que mantenha o mesmo nome) e este arquivo será usado ao invés do gerado por nós.

@gbc921 quando tiver tempo, da uma olhada em como ficou.

**Comment by farosas** [comment]
@gbc921, você citou o issue errado no seu commit. Este issue foi fechado por 15498f. Talvez tenha havido confusão porque eu fiz os comandos \title e \school serem obrigatórios para que o comando \autocitacao tenha o que preencher na autocitação em inglês, mas quando eles não são providos, o erro que acaba sendo emitido não é muito significativo. Em decorrência disso, o seu patch d1115f5 será revertido. 

Vou tentar emitir um erro mais informativo e/ou adicionar mais documentação sobre isso.
